### ISSUE TITLE
Custom Emoji's Dont Work

### ISSUE THREAD

**Issue by michaelrosstarr** [meister03/mongodb-reaction-role#2]
Hi

Great module but I see that custom emoji's are not working? 

Is this a bug, or am I just being really stupid?

Thanks!

**Comment by michaelrosstarr** [comment]
I see that when it is stored to the db, it takes the emoji name, rather store the ID than the emoji itself, cause then it supports all custom emoji's.

I'm going to try to do it myself, but i struggle reading other people's code

**Comment by meister03** [comment]
Yes , you are right, You could join my Discord Server. Then I could give you faster response lol. The link is in the Readme.md
Should I update the package for custom emoji?

**Comment by michaelrosstarr** [comment]
Yeah, custom emoji support should be great!
Shouldn't be that hard to modify the code to use the emoji id rather

**Comment by michaelrosstarr** [comment]
Any update?
Is it in the works?

**Comment by meister03** [comment]
Fix the Issue with A note on #readme.md. I hope this would help you!
